export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';


export const REQUEST_CHARTS_PENDING = 'REQUEST_CHARTS_PENDING';
export const REQUEST_CHARTS_SUCCESS = 'REQUEST_CHARTS_SUCCESS';
export const REQUEST_CHARTS_FAILED = 'REQUEST_CHARTS_FAILED';